apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: njfd867sd-nodejs
  janus-idp.io/tekton: njfd867sd-nodejs
  backstage.io/kubernetes-id: njfd867sd-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: njfd867sd-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
